name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv --only-binary :all: uv==0.6.0
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=aak13-git_python-project-50
            -Dsonar.organization=aak13-git-1
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**